require("custom.statusline").setup()
require("custom.telescope").setup()
require("custom.treesitter-configs").setup()
require("custom.lsp-config").setup()
-- require("custom.dap")
require("custom.comment").setup()
