#!/usr/bin/env zsh

WORKSPACE_3D="~/3d"
D_FRONTEND="$WORKSPACE_3D/device-app-frontend"
D_BACKEND="$WORKSPACE_3D/device-app-backend"
D_DAL="$WORKSPACE_3D/go-dal-client"
T_FRONTEND="$WORKSPACE_3D/tauron-ui"
T_BACKEND="$WORKSPACE_3D/tauron-api"
J_BACKEND="$WORKSPACE_3D/jango"
T_DAL="$WORKSPACE_3D/dal"

WORKSPACE_NATURA="~/natura"
RT_DOWNLOAD="$WORKSPACE_NATURA/commercial-segmentation-calc-relationship-time"
RT_UPLOAD="$WORKSPACE_NATURA/commercial-segmentation-upload-recognition"
RT_CONSUMER_SQS_PYTHON="$WORKSPACE_NATURA/commercial-segmentation-relationship-time"
RT_PRODUCER_SQS_NODE="$WORKSPACE_NATURA/commercial-segmentation-relationship-time-load-sqs"

#PERSONAL_SESSION="vimdeathmatch"
#DEATHMATCH="~/personal/VimDeathmatch/server"
#VWM="~/personal/vim-with-me/v3"
#TVUI="~/work/tvui"
#TVUI_AUTOMATION="~/work/tvui-automation"

createWindow() {
    session=$1
    window=$2
    shift
    shift
    hasWindow=$(tmux list-windows -t $session | grep "$window")
    if [ -z "$hasWindow" ]; then
        cmd="tmux neww -t $session: -n $window -d"
        if [ $# -gt 0 ]; then
            cmd="$cmd $@"
        fi
        echo "Creating Window(\"$hasWindow\"): $cmd"
        eval $cmd
    fi
}

createSession() {
    session=$1
    window=$2
    shift
    shift
    cmd="tmux new -s $session -d -n $window $@ > /dev/null 2>&1"

    echo "Creating Session: $cmd"
    eval $cmd
}

while [ "$#" -gt 0 ]; do
    curr=$1
    shift

    case "$curr" in
    "-d")
        #version=$1
        #if [ -z $version ]; then
        #    echo "-n should have the next argument contain a number"
        #    exit 1
        #fi
        createSession 3DDevice scripts -c $D_FRONTEND
        tmux split-window -t 3DDevice:scripts -c $D_BACKEND
        createWindow 3DDevice frontend -c $D_FRONTEND
        createWindow 3DDevice backend -c $D_BACKEND
        createWindow 3DDevice go-dal-client -c $D_DAL
        ;;
    "-t")
        createSession 3DTauron scripts -c $T_FRONTEND
        tmux split-window -t 3D:scripts -c $T_BACKEND
        createWindow 3DTauron tauron-ui -c $T_FRONTEND
        createWindow 3DTauron tauron-api -c $T_BACKEND
        createWindow 3DTauron ruby-dal -c $T_DAL
        ;;

    "-rt")
        createSession relationship-time scripts -c $RT_PRODUCER_SQS_NODE \; tmux splitw -t relationship-time:scripts -d -c $RT_CONSUMER_SQS_PYTHON
        createWindow relationship-time producer-relationshiptime -c $RT_PRODUCER_SQS_NODE
        createWindow relationship-time consumer-relationshiptime -c $RT_CONSUMER_SQS_PYTHON
        createWindow relationship-time motor-upload -c $RT_UPLOAD
        createWindow relationship-time motor-download -c $RT_DOWNLOAD
        ;;
    # "--vwm")
    #     createSession $PERSONAL_SESSION primary -c $VWM
    #     createWindow $PERSONAL_SESSION vwm -c $VWM "NVIM_LISTEN_ADDRESS=/tmp/nvim2 go run main.go"
    #     ;;
    #
    # "--deathmatch")
    #     createSession $PERSONAL_SESSION primary -c $DEATHMATCH
    #     createWindow $PERSONAL_SESSION server -c $DEATHMATCH/server "docker-compose up --build"
    #     tmux next-window -t $PERSONAL_SESSION:primary
    #     ;;

    *) echo "Unavailable workspace... $curr"
    esac
done
